name: todo_targeting_app
description: A To-Do targeting application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # State Management (Recommended for Clean Arch)
  flutter_bloc: ^8.1.0 
  # Comparison & Value Equality
  equatable: ^2.0.5
  # Dependency Injection
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true